### ISSUE TITLE
Widget twitter

### ISSUE THREAD

**Issue by vickycmcv** [PyLadiesMadrid/pyladies-madrid-website#2]
Nos gustaría incluir un widget de twitter en la web que muestre los últimos tweets del timeline de PyLadies Madrid.

La idea es que estuviese en la Home, pero también estamos abiertas a otras ubicaciones o incluso si pudiese quedarse fijo en todas las páginas de la web.

Aquí está la información de Twitter de cómo hacer widgets para web: https://help.twitter.com/es/using-twitter/embed-twitter-feed

Ejemplos de webs que tienen el componente:

- PyLadies Global: https://pyladies.com/about/
- PyConEs 2019 Alicante: https://2019.es.pycon.org/
- PyBCN: https://pybcn.org/pyladies-bcn/

**Comment by mariamedp** [comment]
@aliciapj en la versión antigua de la web me suena que lo pusiste, puede ser?

**Comment by AndreaFCR** [comment]
Hola! creo que me puedo encargar de esto! Gracias!!!

**Comment by AndreaFCR** [comment]
lo he creado debajo con espacio para añadir el widget de github
