### ISSUE TITLE
Compartir en redes

### ISSUE THREAD

**Issue by vickycmcv** [PyLadiesMadrid/pyladies-madrid-website#4]
La web de PyLadies Madrid es un escaparate de lo que construimos y hacemos entre todas. Por eso queremos incluir botones de compartir en redes sociales en los distintos post del Blog. Así podremos mostrar al mundo lo que vamos haciendo, materiales o proyectos que hagamos en los grupos de trabajo.

Las redes sociales podrían ser Twitter y LinkedIn, y podéis coger los iconos que ya estamos usando en la web.

Ejemplos de web que tienen los botones de compartir en redes sociales:

- Pyladies Global: https://pyladies.com/blog/Announcing-the-Inaugural-PyLadies-Global-Council/inaugural-pyladies-council/
- Women in tech: https://women-in-tech.org/3rd-edition-of-the-women-in-tech-global-awards/

**Comment by AndreaFCR** [comment]
Hola! intento hacer yo esta parte! 👏

**Comment by mariamedp** [comment]
Cerrado en #20. Gracias @AndreaFCR!!! ❤️
